AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  LCNameParam:
    Description: "Launch Configuration Name"
    Type: String

Resources:
  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: 
        - !Select 
          - 0
          - Fn::GetAZs: !Ref "AWS::Region"
      DesiredCapacity: "1"
      LaunchConfigurationName: !Ref LCNameParam
      MaxSize: "1" # Required
      MinSize: "1" # Required
